(()=>{"use strict";
const CFG=window.SONATE_CONFIG||{},ENDPOINT_KEY="sonate-endpoint-v1",DRAFT_KEY="sonate-draft-v24",PENDING_KEY="sonate-pending-v24",$=id=>document.getElementById(id);
let cat="Histoire",rec=null,listening=false,wants=false,base="",endpoint=localStorage.getItem(ENDPOINT_KEY)||"";
const note=$("note"),fields=$("fields"),status=$("status"),badge=$("connectionBadge"),dialog=$("settingsDialog"),endpointInput=$("endpointInput"),settingsStatus=$("settingsStatus");
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const opts=(a=[],ph="Choisir…")=>`<option value="">${ph}</option>`+a.map(v=>`<option>${esc(v)}</option>`).join("");
const field=(id,label,body,full=false)=>`<div class="field ${full?"full":""}"><label for="${id}">${label}</label>${body}</div>`;
function values(){let o={};fields.querySelectorAll("input,select").forEach(x=>o[x.id]=x.value);return o}
function restore(o={}){Object.entries(o).forEach(([k,v])=>{if($(k))$(k).value=v??""})}
function render(saved={}){let L=CFG.lists||{},h="";
if(cat==="Histoire"){h+=field("type","Type",`<select id="type">${opts(L.storyTypes)}</select>`);h+=field("univers","Univers / genre",`<input id="univers" placeholder="Ex. Voxinaë">`);h+=field("saga","Saga",`<input id="saga" placeholder="Facultatif">`);h+=field("sousSaga","Sous-saga",`<input id="sousSaga" placeholder="Facultatif">`);h+=field("cible","Œuvre",`<input id="cible" placeholder="Facultatif / inconnue">`);h+=field("titre","Titre provisoire",`<input id="titre" placeholder="Facultatif">`)}
else if(cat==="Podcast"){h+=field("cible","Podcast",`<select id="cible">${opts(L.podcasts)}</select>`);h+=field("type","Type d’idée",`<select id="type">${opts(L.podcastTypes)}</select>`);h+=field("titre","Titre provisoire",`<input id="titre" placeholder="Facultatif">`,true)}
else if(cat==="Prompt personnage"){h+=field("cible","Projet / application",`<input id="cible" placeholder="Facultatif">`);h+=field("univers","Univers",`<input id="univers" placeholder="Ex. Voxinaë">`);h+=field("personnage","Personnage",`<input id="personnage" placeholder="Ex. Roy Vane">`);h+=field("type","Type de prompt",`<select id="type">${opts(L.promptTypes)}</select>`);h+=field("titre","Titre provisoire",`<input id="titre" placeholder="Facultatif">`,true)}
else if(cat==="Site / outil"){h+=field("cible","Projet / outil",`<input id="cible" placeholder="Ex. Sonate">`);h+=field("type","Type",`<select id="type">${opts(L.toolTypes)}</select>`);h+=field("titre","Titre provisoire",`<input id="titre" placeholder="Facultatif">`,true)}
else{h+=field("type","Type",`<input id="type" placeholder="Facultatif">`);h+=field("cible","Projet / contexte",`<input id="cible" placeholder="Facultatif">`);h+=field("titre","Titre provisoire",`<input id="titre" placeholder="Facultatif">`,true)}
fields.innerHTML=h;restore(saved);fields.querySelectorAll("input,select").forEach(x=>{x.oninput=saveDraft;x.onchange=saveDraft})}
function saveDraft(){localStorage.setItem(DRAFT_KEY,JSON.stringify({cat,note:note.value,fields:values()}));stats()}
function loadDraft(){try{let d=JSON.parse(localStorage.getItem(DRAFT_KEY)||"null");if(d){cat=d.cat||cat;note.value=d.note||"";document.querySelectorAll(".category").forEach(b=>b.classList.toggle("active",b.dataset.cat===cat));render(d.fields||{});$("draftBadge").classList.remove("hidden")}}catch(e){}}
function stats(){let t=note.value.trim(),w=t?t.split(/\s+/).length:0;$("stats").textContent=`${w} mot${w>1?"s":""}`}
document.querySelectorAll(".category").forEach(b=>b.onclick=()=>{let v=values();cat=b.dataset.cat;document.querySelectorAll(".category").forEach(x=>x.classList.toggle("active",x===b));render(v);saveDraft()});note.oninput=saveDraft;$("clearBtn").onclick=()=>{if(confirm("Effacer cette note ?")){note.value="";localStorage.removeItem(DRAFT_KEY);stats()}};
function norm(s){return String(s||"").toLowerCase().replace(/[.,!?;:…]+$/g,"")}
function collapse(t){let a=String(t||"").trim().split(/\s+/).filter(Boolean),o=[];for(let i=0;i<a.length;){let j=i+1;while(j<a.length&&norm(a[j])===norm(a[i]))j++;if(j-i>=3)o.push(a[i]);else for(let k=i;k<j;k++)o.push(a[k]);i=j}return o.join(" ")}
function merge(a,b){let A=String(a||"").trim().split(/\s+/).filter(Boolean),B=String(b||"").trim().split(/\s+/).filter(Boolean);if(!A.length)return B.join(" ");let ov=0;for(let n=Math.min(A.length,B.length);n;n--){let ok=true;for(let i=0;i<n;i++)if(norm(A[A.length-n+i])!==norm(B[i])){ok=false;break}if(ok){ov=n;break}}return [...A,...B.slice(ov)].join(" ")}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){rec=new SR();rec.lang=CFG.language||"fr-FR";rec.continuous=true;rec.interimResults=true;
rec.onstart=()=>{listening=true;base=note.value.trim();$("micBtn").classList.add("listening");$("micLabel").textContent="Arrêter";$("micStatus").textContent="Je t’écoute…";$("micHelp").textContent="Tu peux faire des pauses."};
rec.onresult=e=>{let f="",it="";for(let i=0;i<e.results.length;i++){let p=collapse(e.results[i][0].transcript);if(e.results[i].isFinal)f=merge(f,p);else it=merge(it,p)}note.value=collapse(merge(base,f));$("interim").textContent=it?"… "+it:"";saveDraft()};
rec.onend=()=>{listening=false;$("micBtn").classList.remove("listening");base=note.value.trim();if(wants)setTimeout(()=>{try{if(wants&&!listening)rec.start()}catch(e){}},250);else{$("micLabel").textContent="Dicter";$("micStatus").textContent="Micro en veille"}};
rec.onerror=e=>{if(e.error==="not-allowed")wants=false;$("micStatus").textContent="Micro : "+e.error};$("micBtn").onclick=()=>{try{if(wants){wants=false;if(listening)rec.stop()}else{wants=true;if(!listening)rec.start()}}catch(e){}}}else $("micBtn").disabled=true;
function jsonp(url,timeout=9000){return new Promise((res,rej)=>{let cb="__sonate"+Date.now()+Math.random().toString(36).slice(2),s=document.createElement("script"),timer=setTimeout(()=>{clean();rej(Error("timeout"))},timeout);function clean(){clearTimeout(timer);try{delete window[cb]}catch(e){}s.remove()}window[cb]=d=>{clean();res(d)};s.onerror=()=>{clean();rej(Error("network"))};s.src=url+(url.includes("?")?"&":"?")+"callback="+encodeURIComponent(cb)+"&_="+Date.now();document.head.appendChild(s)})}
function isValidEndpoint(url){
  return /^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec(?:\?.*)?$/.test(String(url || "").trim());
}
function setConnection(state,ver=""){badge.className="connection-badge "+state;if(state==="connected")badge.textContent=`● Pépinière connectée${ver?" · "+ver:""}`;else if(state==="error")badge.textContent="● Connexion Pépinière en erreur";else badge.textContent="● Pépinière non configurée"}
badge.onclick=()=>{endpointInput.value=endpoint;settingsStatus.textContent="";dialog.showModal()};$("closeSettings").onclick=()=>dialog.close();$("saveEndpoint").onclick=()=>{let u=endpointInput.value.trim();if(!isValidEndpoint(u)){settingsStatus.textContent="❌ L’URL doit commencer par https://script.google.com/macros/s/ et se terminer par /exec.";return}endpoint=u;localStorage.setItem(ENDPOINT_KEY,u);setConnection("connected","URL enregistrée");settingsStatus.textContent="✅ URL enregistrée. Le vrai test se fera au prochain dépôt.";setTimeout(()=>dialog.close(),650)};
function makeId(){let d=new Date(),p=n=>String(n).padStart(2,"0");return `BOUT-${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
function payload(old){let f=values(),d=new Date();return{id:old||makeId(),horodatage:d.toISOString(),date:d.toLocaleDateString("fr-FR"),heure:d.toLocaleTimeString("fr-FR"),categorie:cat,type:f.type||"",univers:f.univers||"",saga:f.saga||"",sousSaga:f.sousSaga||"",cible:f.cible||"",titre:f.titre||"",transcription:note.value.trim(),source:"Sonate",statut:"Déposée",metadata:JSON.stringify({personnage:f.personnage||"",appVersion:"2.5.0"})}}
function b64(v){let bytes=new TextEncoder().encode(v),bin="";bytes.forEach(x=>bin+=String.fromCharCode(x));return btoa(bin)}
async function send(p){let enc=b64(JSON.stringify(p)),chunks=[];for(let i=0;i<enc.length;i+=900)chunks.push(enc.slice(i,i+900));for(let i=0;i<chunks.length;i++){status.textContent=`Dépôt ${i+1}/${chunks.length}…`;let u=`${endpoint}?action=depositChunk&id=${encodeURIComponent(p.id)}&part=${i+1}&total=${chunks.length}&data=${encodeURIComponent(chunks[i])}`;let r=await jsonp(u);if(!r?.ok)throw Error(r?.error||"chunk")}let r=await jsonp(`${endpoint}?action=commitDeposit&id=${encodeURIComponent(p.id)}`,12000);if(!r?.ok)throw Error(r?.error||"commit");return r}
function showPending(p){localStorage.setItem(PENDING_KEY,JSON.stringify(p));$("pendingInfo").textContent=`ID ${p.id}. Rien ne sera effacé avant confirmation.`;$("pendingBox").classList.remove("hidden")}
function clearPending(){localStorage.removeItem(PENDING_KEY);$("pendingBox").classList.add("hidden")}
async function deposit(p){if(!endpoint){dialog.showModal();return}if(!p.transcription){status.textContent="La note est vide.";return}showPending(p);$("depositBtn").disabled=true;try{await send(p);let r=await jsonp(`${endpoint}?action=status&id=${encodeURIComponent(p.id)}`);if(r?.found){clearPending();localStorage.removeItem(DRAFT_KEY);note.value="";status.textContent=`🌾 Note déposée et confirmée : ${p.id}`;stats()}else status.textContent="Non confirmé. La note reste sur ce téléphone."}catch(e){status.textContent=`Dépôt non confirmé : ${e.message}. La note reste sauvegardée.`}finally{$("depositBtn").disabled=false}}
$("depositBtn").onclick=()=>deposit(payload());$("retryBtn").onclick=()=>{try{let p=JSON.parse(localStorage.getItem(PENDING_KEY));if(p)deposit(p)}catch(e){}};
try{let p=JSON.parse(localStorage.getItem(PENDING_KEY)||"null");if(p){$("pendingInfo").textContent=`ID ${p.id}. Rien ne sera effacé avant confirmation.`;$("pendingBox").classList.remove("hidden")}}catch(e){}
render();loadDraft();stats();if(endpoint&&isValidEndpoint(endpoint))setConnection("connected","URL enregistrée");else setConnection("unconfigured");
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=2.4").catch(()=>{});
})();